[Environment]
ip = "10.36.56.12"

[Environment.cam_intrinsics]
distance = 27
height = 12
angle = 20

[Register]
some = "/home/pantaelaman/Documents/pi_build/some.py"
other = "/home/pantaelaman/Documents/pi_build/other.py"

[Signals]
init = [
    "other",
    "printip"
]

[[Signals.target_terminated]]
event = "some"
conditions = {name = "!some"}

[Events.other]
targets = ["other"]

[Events.printip]
targets = ["some"]
args = [
    {type="literal", value="-p"},
    {type="literal", value="IP: "},
    {type="literal", value="-l"},
    {type="environment", relation="ip"}
]

[Events.some]
targets = ["some"]
args = [
    {type="literal", value="-l"},
    {type="dynamic", relation="name"}
]
